In [1]:
import numpy as np
l1 = [1,2,3]
array_1 = np.array(l1)
print(type(l1))
print(type(array_1))

<class 'list'>
<class 'numpy.ndarray'>


In [2]:
print(array_1.shape) # >> (3,)으로 나오는 이유는 Tuple은 , 먼저 나올 수 없기 때문이다

# (,3)
# >> 오류

# (3,)
# >> 정상

(3,)


In [3]:
array_2 = np.array(  [[11,22,33],
                      [1,2]]  )

# warning이 아닌 오류가 나면 restart

C:\Users\admin\AppData\Local\Temp\ipykernel_23024\1422353208.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_2 = np.array(  [[11,22,33],


In [4]:
print(array_1.ndim)

1


In [5]:
array1d = np.array([1,2,3])
print('array1d type :', type(array1d))
print('array1d array형태 :', array1d.shape)

array1d type : <class 'numpy.ndarray'>
array1d array형태 : (3,)


In [6]:
array2d = np.array([[1,2,3]])
print('array2d type :', type(array2d))
print('array2d array형태 :', array2d.shape)

array2d type : <class 'numpy.ndarray'>
array2d array형태 : (1, 3)


In [7]:
array3d = np.array([[[1,2,3]]])
print('array3d type :', type(array3d))
print('array3d array형태 :', array3d.shape)

array3d type : <class 'numpy.ndarray'>
array3d array형태 : (1, 1, 3)


In [8]:
print(f'''
array1d :{array1d.ndim:2}차원,
array2d :{array2d.ndim:2}차원,
array3d :{array3d.ndim:2}차원''')


array1d : 1차원,
array2d : 2차원,
array3d : 3차원


### numpy ndarray 자료의 특성

In [9]:
l2 = [1,2,'test']
array2 = np.array(l2)
print(array2, array2.dtype)

l3 = [1,2,3.5]
array3 = np.array(l3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1.  2.  3.5] float64


### 자료형 변환

In [10]:
# int -> float
# float -> int

array_int = np.array([1,2,3]) # integer
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_float2 = np.array([1.1,2.2,3.3]) # float
array_int2 = array_float2.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32


###  ndarray를 편리하게 생성

In [11]:
for i in range(1,5):
    print(i, end=' ')

1 2 3 4 

In [12]:
# np.arange

seq_array = np.arange(0,10)
len(seq_array)
seq_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# reshape
seq_array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
# np.zeros
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [15]:
# np.ones
one_array = np.ones((3,2), dtype='int32')
print(one_array)
print(one_array.dtype, one_array.shape)

[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2)


In [16]:
# 8개 요소 데이터 생성
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))


# 3차원 ndarray -> 2차원 ndarray 로 변환 
array2d = array3d.reshape(-1,1)
array2d

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

---

# 넘파이의 ndarray의 데이터 셋 선택하기 - indexing

In [17]:
# 1. 특정한 데이터만 추출
# 2. 슬라이싱
# 3. 팬시 인덱싱(Fancy)

##### 1. 특정한 데이터만 추출

In [18]:
# 1 ~ 9 까지 array행렬
array1 = np.arange(1,10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# 맨 뒤의 값
print('맨 뒤의 값:', array1[-1],'\n맨 뒤에서 2번째 값:', array1[-2])
array1[-1] = 100
array1

맨 뒤의 값: 9 
맨 뒤에서 2번째 값: 8


array([  1,   2,   3,   4,   5,   6,   7,   8, 100])

In [20]:
# 2차원 데이터 인덱싱
array1d = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# 1,2,4,9의 값들을 호출해주세요
print(array2d[0][0],array2d[0][1],array2d[1][0],array2d[2][2])

1 2 4 9


##### 2. 슬라이싱

In [22]:
array1 = np.arange(1,10)
array1[:3]

array([1, 2, 3])

In [23]:
array2d = array1.reshape(3,3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
print('array2d\n', array2d[:2,:2])

array2d
 [[1 2]
 [4 5]]


In [25]:
# q1. 4 5 6 7 8 9 가져오기
array2d[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [26]:
# q2. 1 4 가져오기(열로)
array2d[:2,:1]

array([[1],
       [4]])

In [27]:
# q3. 1 4 가져오기(행으로) >> 2차원을 1차원으로 차원축소
array2d[:2,0]
# array2d[:2,:1].flatten()

array([1, 4])

##### 3. 팬시 인덱싱(Fancy)

In [28]:
array2d

# array2d[[0,1],2]
print(array2d[[0,1],2])

# array2d[[0,1],0:2]
print(array2d[[0,1],0:2])

# array2d[[0,1]]
print(array2d[[0,1]])

[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]
