In [41]:
# Python 응용 Example

### 목차

[1. Class ](#Class-Example)\
[2. Numpy ](#Numpy-Example)\
[3. Pandas ](#Pandas-Example)\
[4. 예외처리 ](#예외처리)

# Class Example

In [42]:
# Q1. 다음과 같은 기능을 가지는 클래스를 정의하고 인스턴스를 생성하라
# 1. 이름(name)과 나이(age)를 속성으로 가지는 Dog클래스를 정의
# 2. 이름으로 'Mango', 나이로 3의 값을 가지는 my_dog 인스턴스를 생성
# 3. my_dog의 이름과 나이를 다음과 같이 출력하라

# 결과
# my_dog의 이름은 Mango이고, 나이는 3살 입니다.

In [43]:
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age

my_dog = Dog('Mango',3)
print(type(my_dog))
print(f'my_dog의 이름은 {my_dog.name}이고, 나이는 {my_dog.age}살 입니다.')

<class '__main__.Dog'>
my_dog의 이름은 Mango이고, 나이는 3살 입니다.


In [44]:
# Q2.
# 문제에서 정의한 Dog 클래스에 대하여 문자 열화 메소드 __str__()를 구현하여
# print(my_dog)의 출력이 다음과 같이 나타나도록 하여라.

# 결과
# 이름은 Mango이고, 나이는 3살 입니다.

In [45]:
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    def __str__(self):
        return f'my_dog의 이름은 {my_dog.name}이고, 나이는 {my_dog.age}살 입니다.'

my_dog = Dog('Mango',3)
print(my_dog)

my_dog의 이름은 Mango이고, 나이는 3살 입니다.


In [46]:
# Q3. 상속
# UpgradeCalculator
# 다음은 Calculator 클래스이다.

class Calculator:
    def __init__(self):
        self.value = 0
        
    def add(self, val):
        self.value += val
        
# 위 클래스를 상속하는 UpgradeCalculator를 만들고 값을 뺄 수 있는 minus 메소드를 추가하시오.

class UpgradeCalculator(Calculator):
    def minus(self, val):
        self.value -= val
        
cal = UpgradeCalculator()
cal.add(10)
cal.minus(7)

print(cal.value) # 10에서 7을 뺀 3을 출력

3


In [47]:
# Q4. 상속조건
# MaxLimitCalculator
# 객체변수 value가 100이상의 값은 가질 수 없도록 제한하는 클래스이다.

# 실행 결과
'''

cal = MaxLimitCalculator()
cal.add(50) # 50 더하기
cal.add(60) # 60 더하기

print(cal.value) # 100 출력

'''

# 조건 : Calculator 클래스를 상속해서 만들기

class Calculator:
    def __init__(self):
        self.value = 0
        
    def add(self, val):
        self.value += val
        
class MaxLimitCalculator(Calculator):
        def add(self, val):
            super().add(val)
            if self.value >= 100:
                self.value = 100
        
cal = MaxLimitCalculator()
cal.add(50)
cal.add(60)

print(cal.value)

100


In [48]:
# Q5. class 리스트 값 입력
# 다음과 같은 동작하는 클래스를 작성

# 결과
'''

cal1 = Calculator([1,2,3,4,5])
print(cal1.sum()) # 15
print(cal1.avg()) # 3.0

cal2 = Calculator([6,7,8,9,10])
print(cal2.sum()) # 40
print(cal2.avg()) # 8.0


'''

class Calculator:
    def __init__(self, lst):
        self.sum1 = 0
        self.avg1 = 0
        self.lst = lst
        
    def sum(self):
        for i in self.lst:
            self.sum1 += i
        return self.sum1
    
    def avg(self):
        self.avg1 = sum(self.lst)/len(self.lst)
        return self.avg1
        
        

cal1 = Calculator([1,2,3,4,5])
print(cal1.sum())
print(cal1.avg())

cal2 = Calculator([6,7,8,9,10])
print(cal2.sum())
print(cal2.avg())

15
3.0
40
8.0


[목차로 돌아가기](#목차)

# Numpy Example

In [49]:
# Q1.
# 숫자 15에서 23까지 배열을 만들고 이를 3*3 행렬로 변환하여 출력
import numpy as np
q1 = np.arange(15,24).reshape(3,3)
print(q1)

[[15 16 17]
 [18 19 20]
 [21 22 23]]


In [50]:
# Q2.
# 다음의 두 array를 만드시오
# [1 2 3 4]
# [5 6 7 8]
q2_1 = np.arange(1,5)
print(q2_1)

q2_2 = np.arange(5,9)
print(q2_2)


# 위의 두 array를 이용해서 아래와 같은 값이 나오도록 하라
# [False False False False]

print(np.array(q2_1 == q2_2))

[1 2 3 4]
[5 6 7 8]
[False False False False]


In [51]:
# Q3.
# 아래와 같이 3학생의 중간고사, 기말고사 과제의 점수가 있다.

# 이름 = (철수, 영희, 민재)
# 중간고사 = (15,100,45)
# 기말고사 = (78,25,90)
# 과제 = (81,45,99)

name = np.array(['철수','영희','민재'])
mid_test = np.array([15,100,45])
fin_test = np.array([78,25,90])
hw = np.array([81,45,99])


score = np.array(mid_test*0.4 + fin_test*0.4 + hw*0.2 + 5)
print(f'''중간고사 평균 : {mid_test.mean()}
중간고사 표준편차 : {mid_test.std()} ''')

print(f'{name[0]}의 최종 점수는 {score[0]}')

중간고사 평균 : 53.333333333333336
중간고사 표준편차 : 35.19785346990479 
철수의 최종 점수는 58.400000000000006


In [52]:
# Q4.
# 1 에서 10 까지의 정수 값을 가지는 크기가 10인 1차원 배열 a를
# arrange() 함수 사용하여 출력

# 결과
# a = [1 2 3 4 5 6 7 8 9 10]
import numpy as np
a = np.arange(1,11)
print(a)

# 역순 출력
b = a[::-1]
print(b)

# b에 reshape를 사용하여 (2,5) 행렬로 변경하라
c = b.reshape(2,5)
print(c)

# c에 reshape를 사용하여 (5,2) 행렬로 변경하라
d = c.reshape(5,2)
print(d)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]
[[10  9  8  7  6]
 [ 5  4  3  2  1]]
[[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]


In [53]:
# Q5.
# 1에서 16까지의 정수값을 가지는 4x4 크기의 배열을 만들어서 다음과 같이 출력
# 이때 arange와 reshape을 사용하라
q5 = np.arange(1,17).reshape(4,4)
print(q5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [54]:
# Q6.
# random.random을 사용해서 10개의 난수값을 생성하여 다음과 같이 출력하라
# 그리고 이 수들 중 최댓값, 최소값, 평균값을 각각 출력하라
import random
q6 = np.random.random(10)
print(q6)
print(f''' 최대값 : {q6.max()}
최소값 : {q6.min()}
평균값 : {q6.mean()}''')

[0.36573574 0.37229872 0.62101451 0.63668746 0.69075256 0.1214648
 0.89985176 0.16400246 0.94166697 0.74501501]
 최대값 : 0.9416669708107521
최소값 : 0.12146480182847064
평균값 : 0.5558490000432524


In [55]:
# Q7. array 슬라이싱
# 사용자로부터 2이상의 수 n을 입력으로 받아서 모든 원소의 값을 1로 가지는 (n, n) shape 행렬 a를 만드시오
# 그리고 아래 그림과 같이 이 행렬 a의 경계 값을 제외한 내부의 값을 모두 0으로 가지는 행렬 b를 만드시오

# HINT
# p.ones((n, n), dtype='int32')로 모든 원소를 1로 가지는 행렬을 생성한 후 [1:-1, 1:-1] 인덱스를 사용하시오).

'''
실행 결과

n을 입력하시오 : 5
a 행렬
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
b 행렬
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

'''

'\n실행 결과\n\nn을 입력하시오 : 5\na 행렬\n[[1 1 1 1 1]\n [1 1 1 1 1]\n [1 1 1 1 1]\n [1 1 1 1 1]\n [1 1 1 1 1]]\nb 행렬\n[[1 1 1 1 1]\n [1 0 0 0 1]\n [1 0 0 0 1]\n [1 0 0 0 1]\n [1 1 1 1 1]]\n\n'

In [56]:
q7 = int(input('2이상의 n을 입력하시오 :'))
a = np.ones((q7,q7), dtype='int32')
print('a의 행렬','\n',a)

# array copy 동기화
b = a
b[1:-1, 1:-1] = 0
print('b의 행렬','\n',b)

a의 행렬 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
b의 행렬 
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [57]:
# Q8.
# 다음과 같은 두 배열 a와 b가 있을 경우 a배열의 원소내에 b 배열의 원소가 있는지 없는지
# 판단하여 출력하는 프로그램을 작성하시오.
# 이 때 a배열 내의 원소가 b에 있을 경우는 True, 없을경우는 False를 출력

a = np.array([0,10,20,40,60,80])
b = np.array([0,20])

t = np.full(a.shape, False)
ind = 0
for x in a:
    if x in b:
        t[ind] = True
    ind += 1
    
print(t)

[ True False  True False False False]


In [58]:
# Q9. array 슬라이싱
# 다음과 같은 5x5 크기의 2차원 배열 a가 있다. 이 배열을 슬라이싱하여 다음과 같은 배열 b, c, d, e를 완성하여라.
'''
배열 a :
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 2 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]

''' 

a = np.zeros((5,5), dtype='int32')
b = a
b[1:-1, 1:-1] = 1
c = b
c[2,2] = 2
print('배열 a :','\n',a)

배열 a : 
 [[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 2 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [59]:
'''
1) 배열 b :
실행 결과

[[1 1 1]
 [1 2 1]
 [1 1 1]]
'''

b = a[1:4,1:4]
print('배열 b :','\n',b)

배열 b : 
 [[1 1 1]
 [1 2 1]
 [1 1 1]]


In [60]:
'''
2) 배열 c :
실행 결과

[[0 0 0]
 [0 1 1]
 [0 1 2]]
'''

c = a[0:3,0:3]
print('배열 c :','\n',c)

배열 c : 
 [[0 0 0]
 [0 1 1]
 [0 1 2]]


In [61]:
'''
3) 배열 d :
실행 결과

[[0 0 0]
 [1 1 1]
 [1 2 1]]
'''

d = a[0:3,1:4]
print('배열 d :','\n',d)

배열 d : 
 [[0 0 0]
 [1 1 1]
 [1 2 1]]


In [62]:
'''
4) 배열 e :
실행 결과

[[1 1 0]
 [2 1 0]
 [1 1 0]]
'''

e = a[1:4,2:5]
print('배열 e :','\n',e)

배열 e : 
 [[1 1 0]
 [2 1 0]
 [1 1 0]]


In [63]:
'''
5) 배열 f :
실행 결과

[0 1 2 1 0]
'''

f = a[2,:]
print('배열 f :','\n',f)

배열 f : 
 [0 1 2 1 0]


[목차로 돌아가기](#목차)

# Pandas Example

[목차로 돌아가기](#목차)

# 쉬어가는 문제


In [64]:
# Q1.
# ['one','two','three','four']의 단어로 구성된 리스트에서
# 다음과 같이 각 단어의 첫 글자를 대문자로 하는 리스트를 생성하시오

# 실행결과
# ['One','Tow','Three','Four']
# 1. For 문과 슬라이싱, upper() 를 사용하시오

text = ['one','two','three','four']
text_upper = []
for i in text:
    text_upper.append(i[0].upper() + i[1:])
    
text_upper

['One', 'Two', 'Three', 'Four']

In [65]:
# 2. map함수와 람다함수를 사용하여 Q1를 다시 해결하여라
text = ['one','two','three','four']
text_upper = list(map(lambda x: x[0].upper() + x[1:], text))
text_upper

['One', 'Two', 'Three', 'Four']

In [66]:
# 3. 리스트 축약 표현을 이용하여 위의 문제를 해결하여라
text = ['one','two','three','four']
text_upper = [x[0].upper() + x[1:] for x in text]
text_upper

['One', 'Two', 'Three', 'Four']

---

In [67]:
# Q2.
# ['sunday','monday','tuesday','wednesday','thursday','friday','saturday']
# 로 이루어진 리스트로부터 다음과 같은 리스트를 생성하라

# 실행결과
['SUN','MON','TUE','WED','THU','FRI','SAT']

# 1. for 문과 슬라이싱, upper() 를 사용하여 문제를 해결
week = ['sunday','monday','tuesday','wednesday','thursday','friday','saturday']
short_week = []

for i in week:
    short_week.append(i[:3].upper())
    
print(short_week)

['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT']


In [68]:
# 2. map 함수와 람다 함수를 사용하여 해결
short_week = list(map(lambda x : x[:3].upper(), week))
short_week

['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT']

In [69]:
# 3. 리스트 축약을 이용하여 해결
short_week = [x[:3].upper() for x in week]
short_week

['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT']

---

In [70]:
# Q3. Dictionary
# 동윤이가 새로 문을 열고 운영하는 커피 가게에는
# Americano, Ice Americano, Cappuccino, Caffe Latte, Espresso
# 의 5가지 메뉴가 있으며 각 메뉴의 가격은 각각
# 3,000원, 3,500원, 4,000원, 4,500원, 3,600원이다
# 이 목록을 menu라는 딕셔너리로 작성하라.

### 1) 이 menu의 내용을 for key in menu: 구문을 사용하여 다음과 같이 출력하여라.

'''

실행 결과

Americano         가격 : 3,000원
Ice Americano     가격 : 3,500원
Cappuccino        가격 : 4,000원
Cafe Latte        가격 : 4,500원
Espresso          가격 : 3,600원

'''
menu = {'Americano' : 3000, 'Ice Americano' : 3500, 'Cappuccino' : 4000, 'Cafe Latte' : 4500, 'Espresso' : 3600}
menu.get('Americano')
for k in menu.keys():
    print(f'{k}\t 가격 : {menu[k]:,}원')

Americano	 가격 : 3,000원
Ice Americano	 가격 : 3,500원
Cappuccino	 가격 : 4,000원
Cafe Latte	 가격 : 4,500원
Espresso	 가격 : 3,600원


In [71]:
# 2)
# 있는 메뉴라면
# 위의 메뉴 중 하나를 선택하세요 : Espresso
# Espresso는 3,600원 입니다. 결제를 부탁합니다.

# 없는 메뉴라면
# 위의 메뉴 중 하나를 선택하세요 : Fan Cake
# 미안합니다. Fan Cake는 메뉴에 없습니다.

choice = input('Americano, Ice Americano, Cappuccino, Caffe Latte, Espresso 중 하나를 선택하세요 :')
while True:
    if choice in menu:
        print(f'{choice}는 {menu[choice]:,}원 입니다. 결제를 부탁합니다.')
        break
    else:
        print(f'미안합니다. {choice}는 메뉴에 없습니다.')
        break

Espresso는 3,600원 입니다. 결제를 부탁합니다.


In [72]:
# Q4.
# 1)
# 다음과 같은 문자열 리스트로부터 'No.' 부분을 제외한 숫자 부분을 정수 리스트로 반환

# 결과
# test_list = ['No. 224', 'No. 587', 'No. 29', 'No. 37']
# num_list = [224,587,29,37]


test_list = ['No. 224', 'No. 587', 'No. 29', 'No. 37']
num_list = []
for i in test_list:
    num_list.append(int(i.replace('No. ','')))

print(num_list)

[224, 587, 29, 37]


In [73]:
# 2)
# 리스트 축약을 사용하여 출력
num_list = [int(x.replace('No. ', '')) for x in test_list]
num_list

[224, 587, 29, 37]

In [74]:
# Q5.
## 9.10 다음과 같은 기능을 가지는 은행계좌 클래스 BankAccount 클래스를 구현하여라
# 그리고 이 클래스를 이용하여 인스턴스를 생성하여라
# 이 클래스는 다음과 같은 속성과 동작을 가진다.

'''
* 속성
  * 이름(name)
  * 계좌번호(account_num)
  * 잔액(balance)

* 행동
  * 예금 기능 : deposit(money)
    * money 만큼의 돈을 balance에 추가한다.
  * 출금 기능 : withdraw(money)
    * money 만큼의 돈이 balance에서 빠져나간다(balance가 money보다 작으면 출금이 되지 않는다).
'''

class BankAccount:
    def __init__(self, name, account_num, balance = 0):
      self.name = name
      self.account_num = account_num
      self.balance = balance
    
    def get_name():
      return self.name
    def get_account_num():
      return self.account_num
    def get_balance():
      return self.balance
      
    def deposit(self,money):
      self.balance += money
      print(f'{money:,}원이 입금되었습니다. 잔고는 {self.balance:,} 입니다.')
    
    def withdraw(self,money):
      if self.balance - money > 0:
        self.balance -= money
      else:
        print(f'계좌 잔고는 {self.balance:,}원으로 인출 요구 금액 {money:,}원보다 작습니다.')
        
        
    def __str__(self):
      return f'{self.name}님의 계좌 {self.account_num}의 잔고는 {self.balance:,}입니다.'

In [75]:
# BankAccount라는 클래스를 만든 후 다음과 같이 account1이라는 계좌를 생성하고 2000원을 입금하여라
# 이 계좌 정보를 출력한 후 500원을 출금한 후 다음과 같이 계좌 정보를 출력하여라
# 마지막으로 5000원을 출금하여라.


account1 = BankAccount("홍길동", "1234-0001")
print(account1)
account1.deposit(2000)
print(account1)
account1.withdraw(500)
print(account1)
account1.withdraw(5000)

홍길동님의 계좌 1234-0001의 잔고는 0입니다.
2,000원이 입금되었습니다. 잔고는 2,000 입니다.
홍길동님의 계좌 1234-0001의 잔고는 2,000입니다.
홍길동님의 계좌 1234-0001의 잔고는 1,500입니다.
계좌 잔고는 1,500원으로 인출 요구 금액 5,000원보다 작습니다.


[목차로 돌아가기](#목차)

# 4. 예외처리

In [76]:
# a = [1,2,3,4,5]
# a의 원소를 하나 선택하시오 : 삼
# 오류 : 입력 값이 정수나 실수가 아님
a = [1,2,3,4,5]
try:
    num = int(input('a의 원소를 하나 선택하시오>'))
    print(f'{num}은 {a.index(num)+1}번째 원소입니다')

except:
    print('[입력 값이 정수나 실수가 아님]')

[입력 값이 정수나 실수가 아님]


[목차로 돌아가기](#목차)

# 5. 기타 라이브러리

In [77]:
# pip install pillow

In [ ]:
# PIL 모듈에서 몇 개의 클래스를 포함시킨다
from PIL import Image, ImageTk

# tkinter 모듈을 포함시킨다
import tkinter as tk

# 윈도우를 생성하고 윈도우 안에 캔버스를 생성한다
window = tk.Tk()
canvas = tk.Canvas(window, width=500, height=700)
canvas.pack()

#윈도우를 생성하고 윈도우 안에 캔버스를 생성한다
img = Image.open ("C:/Users/admin/Desktop/빅데이터/특강/아바타.jpg")


#tk 형식으로 영상을 변환한다 .
tk_img = ImageTk.PhotoImage(img)

# tkinter의 캔버스에 영상을 표시
canvas.create_image(300, 400, image = tk_img)
window.mainloop()

In [ ]:
from PIL import Image,ImageTk
import tkinter as tk
window = tk.Tk()
canvas = tk.Canvas(window, width=500, height=500)
canvas.pack()

# 영상 파일을 연다
im = Image.open ("C:/Users/admin/Desktop/빅데이터/특강/아바타.jpg")

# 영상을 45 도 회전한다
out = im.rotate(45)

# 영상을 tkinter 형식으로 변환한다
tk_img = ImageTk.PhotoImage(out)

# 영상을 tkinter 에서 화면에 표시한다
canvas.create_image(250, 250, image = tk_img)
window.mainloop()

In [ ]:
from PIL import Image,ImageTk, ImageFilter
import tkinter as tk
window = tk.Tk()
canvas = tk.Canvas(window, width=500, height=500)
canvas.pack()

# 영상 파일을 연다
im = Image.open ("C:/Users/admin/Desktop/빅데이터/특강/아바타.jpg")

# 영상을 흐리게 한다
out = im.filter(ImageFilter.BLUR)

# 영상을 tkinter 형식으로 변환한다
tk_img = ImageTk.PhotoImage(out)

# 영상을 tkinter 에서 화면에 표시한다
canvas.create_image(250, 250, image = tk_img)
window.mainloop()

In [ ]:
# 메뉴 만들기
import tkinter as tk
def open():
    pass

def quit():
    window.quit()

window = tk.Tk()
menubar = tk.Menu(window)
filemenu = tk.Menu(menubar)

filemenu.add_command(label = '열기', command=open)
filemenu.add_command(label = '종료', command=quit)

menubar.add_cascade(label = '파일', menu=filemenu)
window.config(menu = menubar)
window.mainloop()

In [ ]:
from PIL import Image, ImageTk , ImageFilter
import tkinter as tk
from tkinter import filedialog as fd
im = None
tk_img = None

# 파일 메뉴에서 열기를 선택하였을 때 호출되는 함수
def open():
    global im , tk_img
    fname = fd.askopenfilename
    im = Image.open(fname)
    tk_img = ImageTk.PhotoImage(im)
    canvas.create_image(250, 250, image = tk_img)
    window.update()

# 파일 메뉴에서 종료를 선택하였을 때 호출되는 함수
def quit():
    window.quit()

In [ ]:
# 영상처리 메뉴에서 “열기”를 선택하였을 때 호출되는 함수
def image_rotate():
    global im , tk_img
    out = im.rotate(45)
    tk_img = ImageTk.PhotoImage(out)
    canvas.create_image(250, 250, image = tk_img)
    window.update()
    
# 영상처리 메뉴에서 “열기”를 선택하였을 때 호출되는 함수
def image_blur():
    global im , tk_img
    out = im.filter(ImageFilter.BLUR)
    tk_img = ImageTk.PhotoImage(out)
    canvas.create_image(250, 250, image = tk_img)
    window.update()

# 윈도우를 생성한다
window = tk.Tk()
canvas = tk.Canvas(window, width=500, height=500)
canvas.pack()

In [ ]:
# 메뉴를 생성한다
menubar = tk.Menu(window)
filemenu = tk.Menu(menubar)
ipmenu = tk.Menu(menubar)
filemenu.add_command(label= '열기', command=open)
filemenu.add_command(label= '종료', command=quit)
filemenu.add_command(label= '영상회전', command=image_rotate)
filemenu.add_command(label= '영상흐리게', command=image_blur)
menubar.add_cascade(label= '파일', menu = filemenu)
menubar.add_cascade(label= '파일', menu = ipmenu)

window.config(menu=menubar)
window.mainloop()

[목차로 돌아가기](#목차)