# Python 응용

### 목차
[1. Class ](#Class)\
[2. Numpy ](#Numpy)\
[3. Pandas ](#Pandas)\
[4. 예외처리 ](#예외처리)

## Class

In [69]:
# class 는 Field(속성,변수) 와 Method(함수) 로 이루어져 있음

In [70]:
# Example1
class User:
    phone_number = ''
    email_address = ''
    name = ''
    
    def init(self, phone_number, email_address,name):
        self.phone_number = phone_number
        self.email_address = email_address
        self.name = name
    
    def getPhoneNumber(self):
        return self.phone_number

    def getEmail(self):
        return self.email_address

    def getName(self):
        return self.name
    
user1 = User()
user1.init('010-1234-5678', 'engineerk@engineerk.com', 'EngineerK')
print(user1.getPhoneNumber())
print(user1.getEmail())
print(user1.getName())

010-1234-5678
engineerk@engineerk.com
EngineerK


In [71]:
# Example2
class Calculator: # 클래스 Calculator 정의
    def __init__(self): # 초기자(initializer)
        self.result = 0
        
    def add(self,num): # 메소드(method)
        self.result += num
        return self.result

cal1 = Calculator() # 클래스 Calculator의 인스턴스 cal1 생성
cal2 = Calculator() # 클래스 Calculator의 인스턴스 cal1 생성

print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10


In [72]:
# self
class FourCal:
    def setdata(self,first,second):
        self.first = first
        self.second = second

a = FourCal() # 인스턴스 생성

a.setdata(4,2) # 인스턴스 메소드 실행

print(a.first) # = self.first = 4        
print(a.second) # = self.second = 2

FourCal.setdata(a,7,8) # 클래스 메소드로 실행
print(a.first) # = self.first = 7
print(a.second) # = self.second = 8

4
2
7
8


In [73]:
# 클래스 변수와 인스턴스 변수

class FourCal:
    count = 0 # 클래스 변수
    def setdata(self,first,second):
        self.first = first
        self.second = second

    def sum(self):
        result = self.first + self.second
        FourCal.count += 1 # Fourcal.sum을 쓸 때마다 FourCal이라는 클래스의 횟수를 증가시킴
        return result
    
a = FourCal() # 인스턴스 생성
b = FourCal() # 인스턴스 생성

a.setdata(4,2) # 인스턴스 메소드 실행
print(a.first) # = self.first >> 4      
print(a.second) # = self.second >> 2
print(a.sum()) # 메소드 실행, self만 매개변수 >> 6
print(FourCal.count) # 클래스변수 >> 1

b.setdata(7,8) # 인스턴스 메소드 실행
print(b.sum()) # 메소드 실행 >> 15
print(FourCal.count) # 클래스변수 >>2
print(a.sum()) # 메소드 실행 >>6
print(FourCal.count) # 클래스변수 >>3
print(b.sum()) # 메소드 실행 >>15
print(FourCal.count) # 클래스변수 >>4
print(a.count) # = FourCal.count, 클래스변수 >>4
print(b.count) # = FourCal.count, 클래스변수 >>4

4
2
6
1
15
2
6
3
15
4
4
4


In [74]:
# class 클래스명:
#     클래스 속성 = 값
    
#     def __init__(self,*args, *kwargs):
#         self.인스턴스 속성 = 값
        
#     ...

In [75]:
class Daeheeyun:
    
    class_value = 0
    
    def __init__(self):
        self.instance_value = 0
        
    def set_class_value(self):
        Daeheeyun.class_value = 10
        
    def set_instance_value(self):
        self.class_value = 20
        
instance1 = Daeheeyun()
instance2 = Daeheeyun()

print('--클래스 속성 변경--')
instance1.set_class_value()
print(instance1.class_value, instance2.class_value)

print('--인스턴스 속성 변경--')
instance1.set_instance_value()
print(instance1.class_value, instance2.class_value)

print('--속성(Attribute) 출력--')
print(instance1.__dict__)
print(instance2.__dict__)

--클래스 속성 변경--
10 10
--인스턴스 속성 변경--
20 10
--속성(Attribute) 출력--
{'instance_value': 0, 'class_value': 20}
{'instance_value': 0}


In [76]:
# 초기자(생성자, Initializer)

---

In [77]:
# 클래스의 상속
# 상속 : 어떤 클래스를 만들 때 다른 클래스의 기능을 물려받을 수 있게 만드는 것
# class 클래스명(상속할 클래스명)

In [78]:
# Example1
class FourCal:
    def __init__(self, first, second):
        self.first = first
        self.second = second

    def sum(self):
        result = self.first + self.second
        return result
    
class MoreFourCal(FourCal): # FourCal 로 부터 상속받음
    def pow(self):
        result = self.first ** self.second
        return result
    
m = MoreFourCal(4,2)
print(m.pow()) # 현재 클래스 메소드 실행
print(m.sum()) # 부모 클래스 메소드 실행
print(m.first)

16
6
4


In [79]:
# Example2
class Calculator: # 부모 클래스
    def __init__(self, first, second):
        self.first = first
        self.second = second
        
    def add(self):
        result = self.first + self.second
        return result
    
    def mul(self):
        result = self.first * self.second
        return result
    
    def sub(self):
        result = self.first - self.second
    
    def div(self):
        result = self.first / self.second
        return result
    

class Scientific_calculator(Calculator): # 자식 클래스
    pass

Scientific_1 = Scientific_calculator(6,6)
print(Scientific_1.mul())

36


In [80]:
# 만약 같은 이름의 멤버변수나 멤버함수가 부모, 자식클래스에 공통으로 있다면
# 자식클래스의 것으로 덮어쓰기가 됨.
# Example
class BaseClass:
    def myfunc(self):
        print("BaseClass's myfunc")
        
class InhClass(BaseClass):
    def myfunc(self):
        print("InhClass's myfunc")
        

ex1 = BaseClass()
print(ex1.myfunc())

ex2 = InhClass()
print(ex2.myfunc())

## None은 무시 ## print()로 인한 생성텍스트

BaseClass's myfunc
None
InhClass's myfunc
None


---

In [81]:
# 다중 상속
# 여러 개의 부모클래스로부터 상속받을 수 있음
# class 새로운_클래스(베이스클래스1,베이스클래스2, ...):
#     ...
    
# Example
class Base1:
    def myfunc(self):
        print('Base1')
        
    
class Base2:
    member1 = 100
    member2 = 200
    

class Base3:
    def myfunc2(self,a,b):
        print(a+b)
        
        
class InhClass(Base1,Base2,Base3):
    member3 = 300
    
    
ex1 = InhClass()
print(ex1.myfunc())
print(ex1.myfunc2(ex1.member1,ex1.member3))

## None은 무시 ## print()로 인한 생성텍스트

Base1
None
400
None


In [82]:
# 다중 상속시 우선 순위 : mro(메소드 탐색 순서, Method Resolution Order, MRO)

# Example
class A:
    def greeting(self):
        print('안녕하세요. A입니다.')
        
        
class B:
    def greeting(self):
        print('안녕하세요. B입니다.')


class C:
    def greeting(self):
        print('안녕하세요. C입니다.')
        

class D(B,C):
    pass

x=D()
print(x.greeting())

print(D.mro()) # >> 메소드 우선순위 D -> B -> C


안녕하세요. B입니다.
None
[<class '__main__.D'>, <class '__main__.B'>, <class '__main__.C'>, <class 'object'>]


In [83]:
# 메소드 오버라이딩(Overriding, 덮어쓰기)
# 부모 클래스 상속한 클래스 에 있는 메서드를 동일한 이름으로 다시 만드는 것
# 만약 부모 클래스에 정의된 메서드의 이름과 동일한 이름으로 자식 클래스에 생성한다
# 면 부모 클래스의 메서드는 무시되고 자식 클래스의 메서드가 실행

# !!!! super(). 메서드 이름 을 사용해 부모 클래스의 메서드를 호출할 수 있음 !!!!

# Example
class Person:
    def greeting(self):
        print('안녕하세요')
        
        
class Student(Person):
    def greeting(self):
        super().greeting() # 부모 클래스의 메소드 호출
        print('저는 파이썬 코딩 도장 학생입니다') # 추가 메소드
        
        
tom = Person()
print(tom.greeting())

james = Student()
print(james.greeting())

안녕하세요
None
안녕하세요
저는 파이썬 코딩 도장 학생입니다
None


In [84]:
class Data:
    def __init__(self, data):
        tmp = data.split('|') # | 를 기준으로 text 분해
        self.name = tmp[0]
        self.age = tmp[1]
        self.grade = tmp[2]
        
    def print_age(self):
        print(self.age)
        
    def print_grade(self):
        print(f'{self.name}님 당신의 점수는 {self.grade}입니다')
        
data = Data('홍길동|42|A')
data.print_age()

data.print_grade()

42
홍길동님 당신의 점수는 A입니다


---

In [85]:
# '_' 이라는 언더스코어 용도
# 1.
# 인터프리터
# 내 : 마지막 저장값
# 2.
# 값을
# 무시하는 용도로 사용
# 3.
# 네이밍
# : 한 모듈 내부에서만 사용하는 private 클래스 함수 변수 메서드를 선언할 때 사
# 용하는 컨벤션 . from module import 시 로 시작하는 것들은 모두 임포트에서 무시
# ex) __
# init

In [86]:
a = 3
a

3

In [87]:
_ + 5

14

In [88]:
_ * 10

90

In [89]:
x, _, y = (1,2,3) # x = 1, y = 3, 특정값 무시
print(x,y)

1 3


In [90]:
x,*_, y = (1,2,3,4,5) # x = 1, y = 5, 여러개의 값 무시
print(x,y)

1 5


In [91]:
for _ in range(10):
    print('x', end = '') # 인덱스 무시

xxxxxxxxxx

[목차로 돌아가기](#목차)

# Numpy

In [92]:
# 배열 연산, 다차원 데이터 저장 등에 강점
# Array(배열)
# 동일한 자료형을 가지는 값들이 격자판 형태로 이루어짐
# 각 값들은 양의 정수 튜플로 색인(indexing)
# list와 유사하지만 list는 이종의 자료형이 가능하고, 수치연산의 형태가 상이하다.

In [93]:
# Numpy의 ndarray
# vs
# python의 array

# 둘다 리스트이지만 ndarray가 수식활용에 특화된 리스트이다
# x = [1,2,3,4]
# y = [9,8,7,6]
# 일반적으로 x-y는 불가능하지만
# x = np.array(x); x-y는 가능하다
# 이때 type(x) >> numpy.ndarray
# type(y) >> list

In [94]:
# ndarray 속성
import numpy as np
a = np.array([1,2,3])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)
print(a.itemsize)

(3,)
1
int32
3
4


In [95]:
# !!! 중요 !!!
# 1.
# 넘파이 배열 ndarray를 생성할 때, 반드시 대괄호 [] 를 사용하여
# 리스트 형식의 데이터를 만들어야 한다.
a = np.array([1,2,3,4])
# a = np.array(1,2,3,4) >> 오류

In [96]:
# 2.
# 넘파이의 ndarray는 리스트와 달리, 서로 다른 자료형의 값을 원소로 가질 수 없다.
# a = np.array([1,'two', 3, 4], dtype = np.int32) >> 오류

In [97]:
# 다음과 같이 자료형을 명시하지 않을 경우 str형으로 자동형 변환이 일어난다.
# 따라서 덤셈 뺄셈 등의 연산이 사용 불가능 하다.
a = np.array([1,'two', 3, 4])
a

array(['1', 'two', '3', '4'], dtype='<U11')

In [98]:
# 배열과 리스트
a = [2,4,5]
print(a)
a

[2, 4, 5]


[2, 4, 5]

In [99]:
aa =  np.array(a)
print(aa)

[2 4 5]


In [100]:
print(aa[1])
print(a[1])

4
4


---

In [101]:
# 참조 : 배열복사
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
print(arr[5])
print(arr[5:8])

5
[5 6 7]


In [103]:
# 브로드캐스팅, 배열 슬라이스에 스칼라 값을 대입하면
# 그 범위에 값이 전파됨
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [104]:
# 배열 슬라이스는 값을 복사하는게 아니다
# 그러므로 배열 슬라이스의 값을 바꿔도 원본에 반영된다.

arr_slice = arr[5:8]
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [105]:
arr_slice[1] = 12345
print(arr)

[    0     1     2     3     4    12 12345    12     8     9]


In [106]:
arr_slice[:] = 64
print(arr)

[ 0  1  2  3  4 64 64 64  8  9]


In [107]:
# 뷰 대신에 슬라이스의 복사본을 얻고 싶다면
arr_slice_copy = arr[5:8].copy()
print (arr_slice_copy)
print (arr)

[64 64 64]
[ 0  1  2  3  4 64 64 64  8  9]


In [108]:
arr_slice_copy[:] = 8
print (arr_slice_copy)
print (arr)

[8 8 8]
[ 0  1  2  3  4 64 64 64  8  9]


In [109]:
# zeros(), ones(), arange(), eye() 이용 배열
a2 = np.zeros(3)

a2_1 = np.zeros((1,3))

a3 = np.ones(3)
a3_1 = np.ones((1,3))
a3_2 = np.ones([2,3,4])

a4 = np.arange(1,7)

a5 = np.eye(3)


print(a2) # 1 * 3열 1차원 배열 벡터 생성 --> 0으로 된 배열
print(a2_1) # 2차원
print()

print(a3) # 1 * 3열 1차원 배열 벡터 색성 --> 1로 된 배열
print(a3_1) # 2차원
print()
print(a3_2) # 3 * 4열 짜리 2개가 겹쳐진 형태
print()

print(a4) # 1부터 7미만까지 1씩 증가
print()

print(a5) # 단위행렬 3 * 3 생성

[0. 0. 0.]
[[0. 0. 0.]]

[1. 1. 1.]
[[1. 1. 1.]]

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

[1 2 3 4 5 6]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [110]:
# 배열의 차원, 형태
a1 = np.array([1,2,3,4,5,6])
print(a1.ndim) # ndim 배열의 차원, 제일 바깥 []의 개수
print(a1.shape) # shape 배열의 형태 ex) (6,) : 1차원 6개 원소 배열

1
(6,)


In [111]:
# 배열의 형태 변환
c = np.array([1,2,3,4])
c

array([1, 2, 3, 4])

In [112]:
c.shape=(2,2)
c

array([[1, 2],
       [3, 4]])

In [113]:
c.shape=(4,)
c

array([1, 2, 3, 4])

In [114]:
# full() 함수 : 모든 배열의 값을 해당 값으로 채움
b = np.full((2,2),3)
print(b)

[[3 3]
 [3 3]]


In [115]:
# random.random() 0~1사이 임의의 실수 값으로 채워진 배열 생성
k = np.random.random((2,2))
print(k)

[[0.06687874 0.29863366]
 [0.01500147 0.51329611]]


In [116]:
# reshape() 배열 변형
a5 = a4.reshape(3,2) # 3행 2열 형태로 변형
print(a5)


# flatten()  또는    reshape(-1)  또는 ravel()    : 압축
a5_1 = a5.flatten()      # 원본과 동기화가 되지 않음 >> a5의 값을 바꾸어도 a5_1은 바뀌지 않음
a5_2 = a5.reshape(-1)    # 원본과 동기화 됨 >> a5의 값을 바꾸면 a5_2도 바뀜
a5_3 = a5.ravel()        # 원본과 동기화 됨 >> a5의 값을 바꾸면 a5_3도 바뀜


print(a5_1,'\n',a5_2,'\n',a5_3)

a5[0][0] = 100
print(a5)
print(a5_1)
print(a5_2)
print(a5_3)


[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6] 
 [1 2 3 4 5 6] 
 [1 2 3 4 5 6]
[[100   2]
 [  3   4]
 [  5   6]]
[1 2 3 4 5 6]
[100   2   3   4   5   6]
[100   2   3   4   5   6]


In [117]:
# 배열 index
na = np.array([1,2,3,4,5,6,7,8])
print(na.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


In [118]:
a = na.reshape(2,4)
print(a[1,1])   # 1행 1열
print(a[1][1])  # 1행 1열

6
6


In [119]:
# 3차원 배열 생성
array = np.array([
    [[0,1,2,3],
     [4,5,6,7,],
     [8,9,10,11]],
    [[0,1,2,3,],
     [4,5,100,7],
     [8,9,10,11]]
    ])

print(array, array.shape)

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[  0   1   2   3]
  [  4   5 100   7]
  [  8   9  10  11]]] (2, 3, 4)


In [120]:
# 배열 4칙 연산
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# 요소 별 합
print(x+y)
print(np.add(x,y))

# 요소 별 차
print(x-y)
print(np.subtract(x,y))

# 요소 별 곱 ## 행렬 연산이 아님 ##
print(x*y)
print(np.multiply(x,y))

# 행렬 연산(내적곱)
x@y
np.dot(x,y)
x.dot(y)

# 요소 별 나눗셈
print(x/y)
print(np.divide(x,y))

# 요소 별 제곱근
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [121]:
# 배열 행렬 연산
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

v = np.array([9,10])
w = np.array([11,12])

# 벡터의 내적
print(v.dot(w))
print(np.dot(v,w))

# 행렬과 벡터의 곱
print(x.dot(v))
print(np.dot(x,v))

# 행렬 곱
print(x.dot(y))
print(np.dot(x,y))

219
219
[29. 67.]
[29. 67.]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [122]:
# list와 np.array비교
# array 생성
# 인덱싱과 슬라이싱
# 원소 검색
# array 연산

# !! 중요 !!
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [123]:
# 수학 통계 함수
# 자료 타입 : dtype
# 자료 형변환


# !! 중요 !!
ar = np.array([1,2,3,4,5,6])
print(np.argmax(ar))
print(np.argmin(ar))

from numpy import argmax, argmin
print(argmax(ar))
print(argmin(ar))

5
0
5
0


In [124]:
# Example1
import numpy as np
a = np.arange(8).reshape(2,4)
print(a)
print('')
print(np.sum(a, axis = 0))
print(np.sum(a, axis = 1))

[[0 1 2 3]
 [4 5 6 7]]

[ 4  6  8 10]
[ 6 22]


In [125]:
# Exmaple2
import numpy as np
a = np.array([2,4,6,8,10])
idx = np.array([0,0,0,0,1,1,2,2])
c = a[idx]
c

array([2, 2, 2, 2, 4, 4, 6, 6])

[목차로 돌아가기](#목차)

# Pandas

In [126]:
import numpy as np
import pandas as pd

se = pd.Series([1,2, np.nan, 4]) # np.nan은 결측값
print(se.dtype) # 데이터 타입
se

float64


0    1.0
1    2.0
2    NaN
3    4.0
dtype: float64

In [127]:
# 결측치 확인
# np.nan인 결측치 값만 True를 반환
print(se.isna())
se[0], se[1]

0    False
1    False
2     True
3    False
dtype: bool


(1.0, 2.0)

In [128]:
data = [1,2,np.nan,4]
indexed_se = pd.Series(data, index = ['a','b','c','d'])
# 인덱스를 지정해줌

print(data)
print()
print(indexed_se)

[1, 2, nan, 4]

a    1.0
b    2.0
c    NaN
d    4.0
dtype: float64


In [129]:
indexed_se['a'], indexed_se['b'] # 인덱스가 'a', 'b'인 데이터 값

(1.0, 2.0)

In [130]:
indexed_se[0], indexed_se[1] # 인덱스가 0번째 1번째인 값

(1.0, 2.0)

In [131]:
# 데이터를 딕셔너리 형으로 저장했을 경우
# key값이 인덱스, value 값이 데이터 값으로 지정된다.
income = {'1월' : 9500, '2월' : 6200, '3월' : 6050, '4월' : 7000}
income_se = pd.Series(income)
print('동윤이네 상점 수익')
print(income_se)

동윤이네 상점 수익
1월    9500
2월    6200
3월    6050
4월    7000
dtype: int64


In [132]:
from pandas import Series, DataFrame
k = Series([100,101,102,103,104,105])
print(k)

0    100
1    101
2    102
3    103
4    104
5    105
dtype: int64


In [133]:
k1 = Series([100,101,102,103,104,105], index = ['2018-11-01','2018-11-02','2018-11-03','2018-11-04','2018-11-05','2018-11-06'])
print(k1)

2018-11-01    100
2018-11-02    101
2018-11-03    102
2018-11-04    103
2018-11-05    104
2018-11-06    105
dtype: int64


In [134]:
# Series의 index와 values를 통해 원하는 값에 접근 가능
for date in k1.index:
    print(date)
    
for money in k1.values:
    print(money)

2018-11-01
2018-11-02
2018-11-03
2018-11-04
2018-11-05
2018-11-06
100
101
102
103
104
105


In [135]:
# Series의 브로드캐스트 기능 - 인덱스가 달라도 연산가능

# 인덱스가 같은 경우

mine = Series([10,20,30], index = ['korean','english','math'])
friend = Series([70,50,50], index = ['korean','english','math'])

merge = mine + friend
print(merge)

korean     80
english    70
math       80
dtype: int64


In [136]:
# 인덱스가 다른 경우

from pandas import Series, DataFrame

mine = Series([10,20,30], index = ['naver', 'sk', 'kt'])
friend = Series([10,30,20], index = ['kt','naver','sk'])

merge = mine + friend
print(merge)

kt       40
naver    40
sk       40
dtype: int64


In [137]:
# 1. DataFrame 만들기
import numpy as np
import pandas as pd
nparray1 = np.array([[1,2,3,],[4,5,6]]) # numpy array
display(pd.DataFrame(nparray1))

dictionary1 = {'a':['1','3'], 'b' : ['1','2'], 'c' : ['2','4']} # dictionary
display(pd.DataFrame(dictionary1))

0  1  2
0  1  2  3
1  4  5  6

a  b  c
0  1  1  2
1  3  2  4

In [138]:
from pandas import Series, DataFrame
raw_data = {'col0':[1,2,3,4],
            'col1':[10,20,30,40],
            'col2':[100,200,300,400]}

data = DataFrame(raw_data)
print(data)

   col0  col1  col2
0     1    10   100
1     2    20   200
2     3    30   300
3     4    40   400


In [139]:
print(data['col0'])
print(data['col1'])
print(data['col2'])

0    1
1    2
2    3
3    4
Name: col0, dtype: int64
0    10
1    20
2    30
3    40
Name: col1, dtype: int64
0    100
1    200
2    300
3    400
Name: col2, dtype: int64


In [140]:
# Example1

daeshin = {'open':[11650,11100,11200,11100,11000],
           'high':[12100,11000,11200,11100,11150],
           'low':[11600,11050,10900,10950,10900],
           'close':[11900,11600,11000,11100,11050]}

daeshin_day = DataFrame(daeshin)
print(daeshin_day)

    open   high    low  close
0  11650  12100  11600  11900
1  11100  11000  11050  11600
2  11200  11200  10900  11000
3  11100  11100  10950  11100
4  11000  11150  10900  11050


In [141]:
# Example1

# 행의 index 및 cloumns 키워드 지정하기
date = ['16.02.29','16.02.26','16.02.25','16.02.24','16.02.23']
daeshin_day = DataFrame(daeshin, columns = ['open','high','low','close'], index = date)

print(daeshin_day)
print(daeshin_day.columns) # 컬럼명
print(daeshin_day.index) # 인덱스

           open   high    low  close
16.02.29  11650  12100  11600  11900
16.02.26  11100  11000  11050  11600
16.02.25  11200  11200  10900  11000
16.02.24  11100  11100  10950  11100
16.02.23  11000  11150  10900  11050
Index(['open', 'high', 'low', 'close'], dtype='object')
Index(['16.02.29', '16.02.26', '16.02.25', '16.02.24', '16.02.23'], dtype='object')


In [142]:
# 행 및 열 선택
close = daeshin_day['close'] # close라는 열만 선택
print(close)


# print(daeshin_day['16.02.24']) --> 오류
# 인덱스 지정은 다른 함수

16.02.29    11900
16.02.26    11600
16.02.25    11000
16.02.24    11100
16.02.23    11050
Name: close, dtype: int64


In [143]:
# 인덱스 지정
# ~~~.loc[인덱스명]
day_data = daeshin_day.loc['16.02.24']
print(day_data)
print(type(day_data))

open     11100
high     11100
low      10950
close    11100
Name: 16.02.24, dtype: int64
<class 'pandas.core.series.Series'>


In [144]:
dataframe1 = pd.DataFrame(data=[4,5,6,7], index = range(0,4), columns=['A']) # dataframe
print(pd.DataFrame(dataframe1))

series1 = pd.Series({'United Kingdom' : 'London', 'India' : 'New Delhi', 'United States' : 'Washington', 'Belgium' : 'Brussels'})
# Series 는 Pandas 의 벡터 데이터형
print(pd.DataFrame(series1))

   A
0  4
1  5
2  6
3  7
                         0
United Kingdom      London
India            New Delhi
United States   Washington
Belgium           Brussels


In [145]:
# 2. DataFrame 다루기
import numpy as np
import pandas as pd

df = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]), columns = [10,11,12])
print(df)
print('길이 :',len(df))
print('컬럼명 :',df.columns)
df.columns = ['A','B','C']
print(df)

   10  11  12
0   1   2   3
1   4   5   6
2   7   8   9
길이 : 3
컬럼명 : Int64Index([10, 11, 12], dtype='int64')
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [146]:
# 3. 인덱싱과 슬라이싱
print(df['A']) # 컬럼 1개 선택
print(df[['A','B']]) # 컬럼 다중 선택

0    1
1    4
2    7
Name: A, dtype: int32
   A  B
0  1  2
1  4  5
2  7  8


In [147]:
df['B'][0:2] # 'B' 컬럼 중 0~1 인덱스

0    2
1    5
Name: B, dtype: int32

In [148]:
# 인덱스 위치 지정
# ~~~.iloc[인덱스 위치]
print(df.iloc[0]) # index 0 선택
print(df.iloc[0:2]) # index 0~1 선택
print()
print(df.iloc[0:2]['B']) # B컬럼 중 index 0~1선택


# !!!! 중요 !!!!
# 하지만 df.loc[0:2] 는 index 0에서 2까지
# df.iloc[0:2]는 index 0에서 1까지임

A    1
B    2
C    3
Name: 0, dtype: int32
   A  B  C
0  1  2  3
1  4  5  6

0    2
1    5
Name: B, dtype: int32


In [149]:
# 4. 데이터 추가
df = pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]))

# 행 전체를 추가 할 경우 ~~~.loc[인덱스 명] = [데이터 값1, 데이터 값2, ...]
df.loc[3] = [10,11,12]
df.loc[4] = [13,14,15]
print(df)


# 열 전체를 추가 할 경우
df.columns = list('ABC') # 컬럼명 변경
df['D'] = list('ddddd') # 컬럼명으로 추가
print(df)


    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15
    A   B   C  D
0   1   2   3  d
1   4   5   6  d
2   7   8   9  d
3  10  11  12  d
4  13  14  15  d


In [150]:
df[4] = [4]*5
print(df)

df[7] = [7]*5

    A   B   C  D  4
0   1   2   3  d  4
1   4   5   6  d  4
2   7   8   9  d  4
3  10  11  12  d  4
4  13  14  15  d  4


In [151]:
# 5. 데이터 삭제
df = df.drop(7, axis = 1) # 컬럼 삭제
print(df)

    A   B   C  D  4
0   1   2   3  d  4
1   4   5   6  d  4
2   7   8   9  d  4
3  10  11  12  d  4
4  13  14  15  d  4


In [152]:
df = df.drop([4,'D'], axis = 1) # 다중 컬럼 삭제
print(df)

    A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15


In [153]:
df = df.drop(4, axis = 0) # 행 삭제
print(df)

    A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12


In [154]:
df = df.drop([2,3], axis = 0) # 다중 행 삭제
print(df)

   A  B  C
0  1  2  3
1  4  5  6


In [155]:
# 6. 데이터 변경
df.loc[0][0] = 100 # label 기준 변경(불일치시 index 기준)
print(df)

     A  B  C
0  100  2  3
1    4  5  6


In [156]:
df.loc[0]['B'] = 100
print(df)

     A    B  C
0  100  100  3
1    4    5  6


In [157]:
df.iloc[1][1] = 100  # index 기준 변경(불일치시 label 기준)
print(df)

     A    B  C
0  100  100  3
1    4  100  6


In [158]:
df.iloc[1]['C'] = 200
print(df)

     A    B    C
0  100  100    3
1    4  100  200


In [159]:
df.iloc[0][0:2] = [1,2] # 다중 데이터 변경
print(df)

   A    B    C
0  1    2    3
1  4  100  200


In [160]:
df['C'] = [3,6] # 컬럼 변경
print(df)

   A    B  C
0  1    2  3
1  4  100  6


In [161]:
# 7. 데이터 정렬
df = pd.DataFrame({'clutser' : [1,1,2,1,2,3], 'org' : ['a','a','h','c','d','w'],
                   'time' : [8,6,34,23,74,6]}); print(df) # df 생성

df = df.sort_values(['time'], ascending=[False]); print(df) # 'time'컬럼 역순 정렬

df = df.reset_index(drop=True); print(df) # index 재정리

   clutser org  time
0        1   a     8
1        1   a     6
2        2   h    34
3        1   c    23
4        2   d    74
5        3   w     6
   clutser org  time
4        2   d    74
2        2   h    34
3        1   c    23
0        1   a     8
1        1   a     6
5        3   w     6
   clutser org  time
0        2   d    74
1        2   h    34
2        1   c    23
3        1   a     8
4        1   a     6
5        3   w     6


In [162]:
# 8. 기본 함수
df = pd.DataFrame({'clutser' : [1,1,2,1,2,3], 'org' : ['a','a','h','c','d','w'],
                   'time' : [8,6,34,23,74,6]}); print(df) # df 생성

print(df.describe()) # 기초 통계량
print(df.head(2)) # 앞에서 2줄
print(df.tail(3)) # 뒤에서 3줄
print(df.T) # transpose

   clutser org  time
0        1   a     8
1        1   a     6
2        2   h    34
3        1   c    23
4        2   d    74
5        3   w     6
        clutser       time
count  6.000000   6.000000
mean   1.666667  25.166667
std    0.816497  26.445542
min    1.000000   6.000000
25%    1.000000   6.500000
50%    1.500000  15.500000
75%    2.000000  31.250000
max    3.000000  74.000000
   clutser org  time
0        1   a     8
1        1   a     6
   clutser org  time
3        1   c    23
4        2   d    74
5        3   w     6
         0  1   2   3   4  5
clutser  1  1   2   1   2  3
org      a  a   h   c   d  w
time     8  6  34  23  74  6


In [163]:
print(df.time) # 또는 df['time']
print(df[df.time<10])

0     8
1     6
2    34
3    23
4    74
5     6
Name: time, dtype: int64
   clutser org  time
0        1   a     8
1        1   a     6
5        3   w     6


In [164]:
df['time']

0     8
1     6
2    34
3    23
4    74
5     6
Name: time, dtype: int64

In [165]:
# 데이터프레임 Example
month_ex = pd.Series(['1월','2월','3월','4월'])
income_ex = pd.Series([9500, 6200, 6050, 7000])
expenses_ex = pd.Series([5040,2350,2300,4800])

df = pd.DataFrame({'월':month_ex, '수익':income_ex, '지출':expenses_ex})
df

월    수익    지출
0  1월  9500  5040
1  2월  6200  2350
2  3월  6050  2300
3  4월  7000  4800

In [166]:
# 데이터프레임 Example2
path = 'https://github.com/dongupak/DataML/raw/main/csv/'
file = path + 'vehicle_prod.csv'
df = pd.read_csv(file, index_col = 0)
df

2007   2008   2009   2010   2011
China    7.71   7.95  11.96  15.84  16.33
EU      19.02  17.71  15.00  16.70  17.48
US      10.47   8.45   5.58   7.60   8.40
Japan   10.87  10.83   7.55   9.09   7.88
Korea    4.04   3.78   3.45   4.20   4.62
Mexico   2.01   2.05   1.50   2.25   2.54

In [167]:
print(df.columns) # 컬럼명
print(df.index) # 인덱스명

Index(['2007', '2008', '2009', '2010', '2011'], dtype='object')
Index(['China', 'EU', 'US', 'Japan', 'Korea', 'Mexico'], dtype='object')


In [168]:
print(df.columns.tolist()) # 컬럼들을 리스트형으로 반환
print(df['2007'].tolist()) # 2007년도 컬럼의 값들을 리스트형으로 반환

['2007', '2008', '2009', '2010', '2011']
[7.71, 19.02, 10.47, 10.87, 4.04, 2.01]


In [169]:
# 새로운 열 생성 : total값 구하기
df['total'] = df.sum(axis = 1)
df['mean'] = df.mean(axis = 1)
df

2007   2008   2009   2010   2011  total       mean
China    7.71   7.95  11.96  15.84  16.33  59.79  19.930000
EU      19.02  17.71  15.00  16.70  17.48  85.91  28.636667
US      10.47   8.45   5.58   7.60   8.40  40.50  13.500000
Japan   10.87  10.83   7.55   9.09   7.88  46.22  15.406667
Korea    4.04   3.78   3.45   4.20   4.62  20.09   6.696667
Mexico   2.01   2.05   1.50   2.25   2.54  10.35   3.450000

In [170]:
df.drop('2007', inplace = True, axis = 1) # 2007년인 컬럼 삭제
df['total'] = df[['2008','2009','2010','2011']].sum(axis=1) # 2008년 부터 합계 다시 구하기
df['mean'] = df[['2008','2009','2010','2011']].mean(axis=1) # 2008년 부터 평균 다시 구하기
df

2008   2009   2010   2011  total     mean
China    7.95  11.96  15.84  16.33  52.08  13.0200
EU      17.71  15.00  16.70  17.48  66.89  16.7225
US       8.45   5.58   7.60   8.40  30.03   7.5075
Japan   10.83   7.55   9.09   7.88  35.35   8.8375
Korea    3.78   3.45   4.20   4.62  16.05   4.0125
Mexico   2.05   1.50   2.25   2.54   8.34   2.0850

In [171]:
df.loc['total'] = df.sum(axis = 0) # total이라는 행 추가(합계를 통해)
df

2008   2009   2010   2011   total     mean
China    7.95  11.96  15.84  16.33   52.08  13.0200
EU      17.71  15.00  16.70  17.48   66.89  16.7225
US       8.45   5.58   7.60   8.40   30.03   7.5075
Japan   10.83   7.55   9.09   7.88   35.35   8.8375
Korea    3.78   3.45   4.20   4.62   16.05   4.0125
Mexico   2.05   1.50   2.25   2.54    8.34   2.0850
total   50.77  45.04  55.68  57.25  208.74  52.1850

In [172]:
df.drop('Mexico', axis=0, inplace = True) # 'Mexico'행 삭제, 원본에 동기화
df

2008   2009   2010   2011   total     mean
China   7.95  11.96  15.84  16.33   52.08  13.0200
EU     17.71  15.00  16.70  17.48   66.89  16.7225
US      8.45   5.58   7.60   8.40   30.03   7.5075
Japan  10.83   7.55   9.09   7.88   35.35   8.8375
Korea   3.78   3.45   4.20   4.62   16.05   4.0125
total  50.77  45.04  55.68  57.25  208.74  52.1850

In [173]:
# 위의 파일 다시 불러오기
df = pd.read_csv(file, index_col = 0)
df.head()

2007   2008   2009   2010   2011
China   7.71   7.95  11.96  15.84  16.33
EU     19.02  17.71  15.00  16.70  17.48
US     10.47   8.45   5.58   7.60   8.40
Japan  10.87  10.83   7.55   9.09   7.88
Korea   4.04   3.78   3.45   4.20   4.62

In [174]:
print(df[2:6])
print(df.loc['Korea'])
print(df.loc[['US','Korea']])
print(df['2011'][[0,4]])
print(df.loc['Korea','2011'])

         2007   2008  2009  2010  2011
US      10.47   8.45  5.58  7.60  8.40
Japan   10.87  10.83  7.55  9.09  7.88
Korea    4.04   3.78  3.45  4.20  4.62
Mexico   2.01   2.05  1.50  2.25  2.54
2007    4.04
2008    3.78
2009    3.45
2010    4.20
2011    4.62
Name: Korea, dtype: float64
        2007  2008  2009  2010  2011
US     10.47  8.45  5.58   7.6  8.40
Korea   4.04  3.78  3.45   4.2  4.62
China    16.33
Korea     4.62
Name: 2011, dtype: float64
4.62


---

In [175]:
# 데이터프레임 Example3
weather_file = path + 'weather.csv'
weather = pd.read_csv(weather_file, index_col = 0, encoding = 'cp949')

print(weather.shape) # (행,열)
weather

(3653, 3)


평균기온  최대풍속  평균풍속
일시                          
2010-08-01  28.7   8.3   3.4
2010-08-02  25.2   8.7   3.8
2010-08-03  22.1   6.3   2.9
2010-08-04  25.3   6.6   4.2
2010-08-05  27.2   9.1   5.6
...          ...   ...   ...
2020-07-27  22.1   4.2   1.7
2020-07-28  21.9   4.5   1.6
2020-07-29  21.6   3.2   1.0
2020-07-30  22.9   9.7   2.4
2020-07-31  25.7   4.8   2.5

[3653 rows x 3 columns]

In [176]:
# weather.describe()
print('평균------------------')
print(weather.mean())
print('표준편차---------------')
print(weather.std())

평균------------------
평균기온    12.942102
최대풍속     7.911099
평균풍속     3.936441
dtype: float64
표준편차---------------
평균기온    8.538507
최대풍속    3.029862
평균풍속    1.888473
dtype: float64


In [177]:
weather.count()

평균기온    3653
최대풍속    3649
평균풍속    3647
dtype: int64

In [178]:
# 결측치 파악
missing_data = weather[weather['평균풍속'].isna()]
print(missing_data)

# 결측치 총 개수
print(weather.isna().sum())

            평균기온  최대풍속  평균풍속
일시                          
2012-02-11  -0.7   NaN   NaN
2012-02-12   0.4   NaN   NaN
2012-02-13   4.0   NaN   NaN
2015-03-22  10.1  11.6   NaN
2015-04-01   7.3  12.1   NaN
2019-04-18  15.7  11.7   NaN
평균기온    0
최대풍속    4
평균풍속    6
dtype: int64


In [179]:
# 결측치 처리
# 1. 삭제
print(weather.dropna(axis=0, inplace = False).isna().sum()) # inplace = False 한 이유 : 뒤에 데이터를 계속 쓰려고

평균기온    0
최대풍속    0
평균풍속    0
dtype: int64


In [180]:
# 2. 0으로 대체
weather.fillna(0, inplace = True)
print(weather.loc['2012-02-11'])

평균기온   -0.7
최대풍속    0.0
평균풍속    0.0
Name: 2012-02-11, dtype: float64


In [181]:
# 3. 평균값으로 대체
weather.fillna(weather['평균풍속'].mean(), inplace = True)
print(weather.loc['2012-02-11'])

평균기온   -0.7
최대풍속    0.0
평균풍속    0.0
Name: 2012-02-11, dtype: float64


---

In [182]:
# 시계열 데이터
d_list = ['01/03/2018', '01-03-2018','2018-01-05', '2018/01/06']
print(pd.DatetimeIndex(d_list).year)    # 년도 값을 출력함
print(pd.DatetimeIndex(d_list).month)   # 월 값을 출력함
print(pd.DatetimeIndex(d_list).day)     # 일 값을 출력함

Int64Index([2018, 2018, 2018, 2018], dtype='int64')
Int64Index([1, 1, 1, 1], dtype='int64')
Int64Index([3, 3, 5, 6], dtype='int64')


In [183]:
dt_list = ['01,03,2018 11:12:13', '01-03-2018 11:22:13']
print(pd.DatetimeIndex(dt_list).hour)      # 시 값을 출력함
print(pd.DatetimeIndex(dt_list).minute)    # 분 값을 출력함

Int64Index([11, 11], dtype='int64')
Int64Index([12, 22], dtype='int64')


In [184]:
weather = pd.read_csv(weather_file, encoding = 'cp949')
weather['일시'] = pd.DatetimeIndex(weather['일시']).year
weather

일시  평균기온  최대풍속  평균풍속
0     2010  28.7   8.3   3.4
1     2010  25.2   8.7   3.8
2     2010  22.1   6.3   2.9
3     2010  25.3   6.6   4.2
4     2010  27.2   9.1   5.6
...    ...   ...   ...   ...
3648  2020  22.1   4.2   1.7
3649  2020  21.9   4.5   1.6
3650  2020  21.6   3.2   1.0
3651  2020  22.9   9.7   2.4
3652  2020  25.7   4.8   2.5

[3653 rows x 4 columns]

In [185]:
weather['month'] = pd.DatetimeIndex(weather['일시']).month
monthly_means = weather.groupby('month').mean()
print(monthly_means)

                일시       평균기온      최대풍속      평균풍속
month                                            
1      2015.081577  12.942102  7.911099  3.936441


In [186]:
# 데이터 구조를 변경하는 pivot()

df = pd.DataFrame({'상품':['시계','반지','반지','목걸이','팔찌'],
                   '재질':['금','은','백금','금','은'],
                   '가격':[500000,20000,350000,300000,60000]})

df

상품  재질      가격
0   시계   금  500000
1   반지   은   20000
2   반지  백금  350000
3  목걸이   금  300000
4   팔찌   은   60000

In [187]:
new_df = df.pivot(index = '상품',columns='재질', values = '가격')
new_df.fillna(value = 0) # pivot을 할 때 연속이 아닌 범주형인 값을 index로 놓는것이 편하다(연속형일 경우 테이블이 매우 커짐)

재질          금        백금        은
상품                              
목걸이  300000.0       0.0      0.0
반지        0.0  350000.0  20000.0
시계   500000.0       0.0      0.0
팔찌        0.0       0.0  60000.0

In [188]:
# 두 개의 데이터프레임을 하나로 합치는 concat()
df_1 = pd.DataFrame({'A' : ['a10', 'a11','a12'],
                     'B' : ['b10', 'b12','b13'],
                     'C' : ['c10', 'c11','c12']},
                    index = ['가','나','다'])

df_2 = pd.DataFrame({'B' : ['b23','b24','b25'],
                     'C' : ['c23','c24','c25'],
                     'D' : ['d23','d24','d25']},
                    index = ['다','라','마'])

In [189]:
print(df_1)
print(df_2)

     A    B    C
가  a10  b10  c10
나  a11  b12  c11
다  a12  b13  c12
     B    C    D
다  b23  c23  d23
라  b24  c24  d24
마  b25  c25  d25


In [190]:
df_3 = pd.concat([df_1,df_2])
print(df_3)

     A    B    C    D
가  a10  b10  c10  NaN
나  a11  b12  c11  NaN
다  a12  b13  c12  NaN
다  NaN  b23  c23  d23
라  NaN  b24  c24  d24
마  NaN  b25  c25  d25


In [191]:
df_4 = pd.concat([df_1,df_2], join = 'inner')
print(df_4)

     B    C
가  b10  c10
나  b12  c11
다  b13  c12
다  b23  c23
라  b24  c24
마  b25  c25


In [192]:
# concat()은 Pandas 함수로, 결합을 위하여 하나 이상의 데이터프레임을 인자로 받음
# merge()는 데이터프레임의 메소드이며, 두 데이터프레임을 각 데이터에 존재하는 고유값(key)을 기준으로 병합할 때 사용한다.

print('left outer \n', df_1.merge(df_2, how = 'left', on = 'B'), '\n')
print('right outer \n', df_1.merge(df_2, how='right', on='B'), '\n')
print('full outer \n', df_1.merge(df_2, how='outer', on='B'), '\n')
print('inner \n', df_1.merge(df_2, how='inner', on='B'))

left outer 
      A    B  C_x  C_y    D
0  a10  b10  c10  NaN  NaN
1  a11  b12  c11  NaN  NaN
2  a12  b13  c12  NaN  NaN 

right outer 
      A    B  C_x  C_y    D
0  NaN  b23  NaN  c23  d23
1  NaN  b24  NaN  c24  d24
2  NaN  b25  NaN  c25  d25 

full outer 
      A    B  C_x  C_y    D
0  a10  b10  c10  NaN  NaN
1  a11  b12  c11  NaN  NaN
2  a12  b13  c12  NaN  NaN
3  NaN  b23  NaN  c23  d23
4  NaN  b24  NaN  c24  d24
5  NaN  b25  NaN  c25  d25 

inner 
 Empty DataFrame
Columns: [A, B, C_x, C_y, D]
Index: []


In [193]:
df_3 = df_1.merge(df_2, how = 'outer', on = 'B')
print(df_3)

     A    B  C_x  C_y    D
0  a10  b10  c10  NaN  NaN
1  a11  b12  c11  NaN  NaN
2  a12  b13  c12  NaN  NaN
3  NaN  b23  NaN  c23  d23
4  NaN  b24  NaN  c24  d24
5  NaN  b25  NaN  c25  d25


In [194]:
df_3 = df_1.merge(df_2, how = 'outer',
                  left_index = True, right_index = True)
print(df_3)

     A  B_x  C_x  B_y  C_y    D
가  a10  b10  c10  NaN  NaN  NaN
나  a11  b12  c11  NaN  NaN  NaN
다  a12  b13  c12  b23  c23  d23
라  NaN  NaN  NaN  b24  c24  d24
마  NaN  NaN  NaN  b25  c25  d25


In [195]:
df = pd.read_csv('C:/Users/admin/Desktop/빅데이터/2주차 _ 파이썬(전홍배교수)/data/data.csv')

df.loc[3] = [23,165,56] # 행추가
df


number  height  weight
0      32     179      81
1       1     181      46
2      23     154      67
3      23     165      56

In [196]:
df.to_csv('data2.csv') # 파일 저장

In [197]:
# pip install --user pandas-profiling
# pip install ipywidgets

In [ ]:
import pandas as pd
import pandas_profiling as pp
import ipywidgets

df = pd.read_csv('C:/Users/admin/Desktop/빅데이터/2주차 _ 파이썬(전홍배교수)/data/Heart.csv')
df.tail(12)
ppr = pp.ProfileReport(df)
ppr.to_widgets()
ppr.to_notebook_iframe()
ppr.to_file(output_file='Heart.ppr.html')

[목차로 돌아가기](#목차)

# 4. 예외처리

- 문법오류(StntaxError)
- 파일 없음 오류(FileNotFoundError)


In [199]:
# try:
#     에러가 의심가는 코드
# except:
#     에러 발생시 수행할 코드
# else:
#     에러가 발생하지 않았으면 수행할 코드
# finally:
#     에러가 발생했던 안했던 무조건 수행할 코드

In [200]:
# 오류시 종료
fname = input('[내용 확인하고 싶은 파일 이름을 입력하세요] >')

while fname:  #fname이 제대로 입력되면 반복(오류시 종료)
    try:
        myfile = open(fname,'r')
        print(myfile.read())
        fname = input('> \n[내용 확인하고 싶은 파일 이름을 입력하세요] >')
    except FileNotFoundError:
        print('[오류메시지] 파일이 존재하지 않습니다.')
        fname=''
    

[오류메시지] 파일이 존재하지 않습니다.


In [201]:
# 반복
fname = input('[내용 확인하고 싶은 파일 이름을 입력하세요] > ')
while fname: # fname이 제대로 입력되면 반복 (Null 이면 종료)
    try:
        myfile = open(fname,'r')
    except FileNotFoundError: # 오류인 경우 다시 입력 요청
        fname = input('[오류] 파일 이름을 다시 입력하세요: > ')
    else:
        print(myfile.read()) # 정상인 경우 출력하고 다시 반복
        fname = input('> \n[내용 확인하고 싶은 파일 이름을 입력하세요] > ')


In [202]:
# 날짜 오류1

days = (31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
date=True

while date: # date 값이 True인 경우 반복 (Null 이면 종료)
    try:
        date = input('날짜 <월 일>을 입력하세요: > ')
        mm, dd = date.split()
        mm, dd = int(mm), int(dd)
        while mm<1 or mm>12 or dd<1 or dd>days[mm-1]: # 범위 확인
            date = input('[월/일-오류] 다시 입력하세요: > ')
            mm, dd = date.split()
            mm, dd = int(mm), int(dd)

    except : # 입력 오류시 오류 메시지 출력
        print('[입력 오류]')
    else: # 정상 입력시 월-일 출
        print('%d월 %d일'%(mm, dd))
        mm = False

[입력 오류]


In [203]:
# 날짜 오류2

days = (31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
date=True
while date: # date 값이 True인 경우 반복 (Null 이면 종료)
    try:
        date = input('날짜 <월 일>을 입력하세요: > ')
        mm, dd = date.split()
        mm, dd = int(mm), int(dd)
        if mm < 1 or mm > 12 : # 범위 오류시 ValueError 발생
            raise ValueError('월은 1에서 12 까지')
        if dd < 1 or dd > days[mm-1]: # 범위 오류시 ValueError 발생
            raise ValueError('일은 1에서 %d 까지'%days[mm-1])
    
    except ValueError as e: # 입력 값 오류시 오류 메시지 출력
        print('[입력 오류]', e)
    
    else: # 정상 입력시 월-일 출력
        print('%d월 %d일'%(mm, dd))
        
# except ValueError as e: # 어떤 오류가 날지 알 수 없는 상황에서, 그 오류e를 출력
#     print('[입력 오류]', e)

[입력 오류] not enough values to unpack (expected 2, got 0)


In [204]:
# raise : 강제 오류 발생
fruit = ['apple','banana','grape','watermelon']
print(fruit)

while True:
    index = input('과일 색인 값 선택:')
    
    try:
        index = int(index)
        
        
        if index == 1:
            raise NameError
        
        else:
            print(fruit[index])
            
    except NameError:
        print('바나나는 불가능합니다')
        
    
    except IndexError:
        print('해당 색인은 호출할 수 없습니다')
        
    
    except ValueError:
        print('소수점은 사용할 수 없습니다.')
        
    print('--------------------------')

['apple', 'banana', 'grape', 'watermelon']
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
--------------------------
소수점은 사용할 수 없습니다.
----------------

In [ ]:
# 사용자 정의 오류
class NumberCheckError(Exception):
    def __init__(self, msg = 'Error'):
        self.msg = msg
    def __str__(self):
        return self.msg
    
try:
    number = int(input('숫자를 입력하세요> '))
    if number < 0:
        raise NumberCheckError('0보다 작습니다.')
    
except NumberCheckError as e:
    print(e)

In [ ]:
# 사용자 정의 오류 발생
class AdminError(Exception):
    pass

while True:
    admin = input('관리자 계정 입력: ')
    
    try:
        if admin != 'yundaehee':
            raise AdminError()
        
        else:
            print('관리자 계정입니다')
        
        
    except AdminError:
        print('관리자 계정이 아닙니다')
    
    print('-------------------')

[목차로 돌아가기](#목차)

In [ ]:
import re
with open('C:/Users/admin/Desktop/빅데이터/2주차 _ 파이썬(전홍배교수)/data/news.txt', mode='r') as file:
    text = file.read()
    
    # 숫자만 뽑아, 리스트로 출력
    ex1 = r'\d'
    print('ex1 : ', re.findall(ex1, text)) 
    
    # 영어 단어만 뽑기
    ex2 = r'([a-zA-Z]+)'
    print('ex2 : ', re.findall(ex2, text))
    
    # '베트남'을 포함하는 단어들을 뽑기
    ex3 = r'\s베트남[가-힝]'
    print('ex3 : ', re.findall(ex3, text)) 